site_name: My Docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette: 
    - primary: white
      accent: light blue
      toggle:
        icon: material/lightbulb-off-outline 
        name: Switch to dark mode
    - primary: black
      accent: light blue
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate
repo_url: https://github.com/mmdjiji/mkdocs-template
repo_name: mmdjiji/mkdocs-template
edit_uri: edit/main/docs/
markdown_extensions:
  - admonition              # 提示块
  - footnotes               # 脚注
  - meta                    # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret          # 下划线上标
  - pymdownx.tilde          # 删除线下标
  - pymdownx.critic         # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details        # 提示块可折叠
  - pymdownx.inlinehilite   # 行内代码高亮
  - pymdownx.mark           # 文本高亮
  - pymdownx.smartsymbols   # 符号转换
  - pymdownx.superfences    # 代码嵌套在列表里
  - codehilite:             # 代码高亮，显示行号
      guess_lang: true
      linenums: true
  - toc:                    # 锚点
      permalink: true
  - pymdownx.arithmatex     # 数学公式
  - pymdownx.betterem:      # 对加粗和斜体更好的检测
      smart_enable: all
  - pymdownx.magiclink      # 自动识别超链接
  - pymdownx.tasklist:      # 复选框checklist
      custom_checkbox: true
extra:
  homepage: https://github.com/mmdjiji/mkdocs-template